# Generated by Django 5.2.3 on 2025-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro')], default='standard', help_text='План подписки пользователя', max_length=20),
        ),
    ]
