# Generated by Django 5.2.3 on 2025-06-23 17:20

import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub')),
                ('project_public_link', models.URLField(validators=[projects.models.validate_https_url], verbose_name='Публичная ссылка на проект')),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='projects/photos/', verbose_name='Изображение проекта')),
                ('status', models.CharField(choices=[('public', 'Публичный'), ('profile_only', 'Виден только в профиле'), ('private', 'Закрытый')], default='public', max_length=20, verbose_name='Статус проекта')),
                ('technologies', models.JSONField(default=list, help_text='Список технологий в формате JSON', verbose_name='Технологии')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Количество комментариев')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL-путь')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='projects_pr_status_7ee874_idx'), models.Index(fields=['author', 'status'], name='projects_pr_author__37eecb_idx'), models.Index(fields=['slug'], name='projects_pr_slug_042165_idx')],
            },
        ),
    ]
