# Generated by Django 5.2.3 on 2025-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Премиум пользователь с расширенными возможностями'),
        ),
    ]
