# Generated by Django 5.2.3 on 2025-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_update_default_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='css_file_key',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='html_file_key',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='js_file_key',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='js_content',
            field=models.TextField(default='// JavaScript код\nconsole.log("Portfolio loaded!");\n\n// Ждем загрузки DOM\ndocument.addEventListener("DOMContentLoaded", function() {\n    console.log("DOM ready");\n    \n    const title = document.getElementById("title");\n    const button = document.getElementById("clickBtn");\n    \n    if (title) {\n        title.addEventListener("click", function() {\n            title.style.color = title.style.color === "yellow" ? "white" : "yellow";\n        });\n    }\n    \n    if (button) {\n        button.addEventListener("click", function() {\n            alert("Button clicked!");\n            button.textContent = "Works great!";\n        });\n    }\n});'),
        ),
    ]
