# Generated by Django 5.2.3 on 2025-07-09 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('project_notifications', models.BooleanField(default=True, verbose_name='Уведомления о проектах')),
                ('like_comment_notifications', models.BooleanField(default=True, verbose_name='Уведомления о лайках и комментариях')),
                ('template_notifications', models.BooleanField(default=True, verbose_name='Уведомления о новых шаблонах')),
                ('weekly_newsletter', models.BooleanField(default=True, verbose_name='Еженедельная рассылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Локация')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой'), ('prefer_not_to_say', 'Предпочитаю не указывать')], max_length=20, verbose_name='Пол')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Социальные ссылки')),
                ('profile_visibility', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Видимость профиля')),
                ('projects_visibility', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Видимость проектов')),
                ('portfolio_visibility', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Видимость портфолио')),
                ('notify_new_followers', models.BooleanField(default=True, verbose_name='Уведомления о новых подписчиках')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-last_activity'],
            },
        ),
    ]
