# Generated by Django 5.2.3 on 2025-07-09 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='first_login_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Первый вход'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_trusted',
            field=models.BooleanField(default=False, verbose_name='Доверенная сессия'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='trusted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время получения доверия'),
        ),
    ]
