# Generated by Django 5.2.3 on 2025-07-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_usersession_first_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='jwt_token_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хеш JWT токена'),
        ),
    ]
