# Generated by Django 5.2.3 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='css_content',
            field=models.TextField(default="/* Ваши CSS стили */\n.container {\n    font-family: 'Arial', sans-serif;\n    max-width: 800px;\n    margin: 0 auto;\n    padding: 20px;\n    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n    min-height: 100vh;\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n    color: white;\n}\n\nh1 {\n    font-size: 3rem;\n    margin-bottom: 1rem;\n    text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\n}\n\np {\n    font-size: 1.2rem;\n    line-height: 1.6;\n    margin-bottom: 2rem;\n    text-align: center;\n}\n\nbutton {\n    background: white;\n    color: #667eea;\n    border: none;\n    padding: 12px 24px;\n    font-size: 1rem;\n    border-radius: 25px;\n    cursor: pointer;\n    transition: all 0.3s ease;\n    font-weight: bold;\n}\n\nbutton:hover {\n    transform: translateY(-2px);\n    box-shadow: 0 5px 15px rgba(0,0,0,0.2);\n}"),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='html_content',
            field=models.TextField(default='<div class="container">\n    <h1 id="title">Привет, мир!</h1>\n    <p>Это мой первый проект портфолио.</p>\n    <button id="clickBtn">Нажми меня!</button>\n</div>'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='js_content',
            field=models.TextField(default='// Ваш JavaScript код\nconsole.log("Привет из портфолио!");\n\n// Ждем загрузки DOM\ndocument.addEventListener("DOMContentLoaded", function() {\n    console.log("DOM загружен");\n    \n    const title = document.getElementById("title");\n    const button = document.getElementById("clickBtn");\n    \n    if (title) {\n        title.addEventListener("click", function() {\n            title.style.color = title.style.color === "yellow" ? "white" : "yellow";\n        });\n    }\n    \n    if (button) {\n        button.addEventListener("click", function() {\n            alert("Привет! Это работает!");\n            button.textContent = "Отлично работает!";\n        });\n    }\n});'),
        ),
    ]
