# Generated by Django 5.2.3 on 2025-07-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefile',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL для доступа к файлу', max_length=1000, null=True),
        ),
    ]
