# Generated by Django 5.2.3 on 2025-06-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное имя компонента', max_length=100)),
                ('display_name', models.CharField(help_text='Отображаемое имя', max_length=100)),
                ('category', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('about', 'About'), ('cta', 'Call to Action'), ('footer', 'Footer'), ('navigation', 'Navigation')], max_length=50)),
                ('industry', models.CharField(choices=[('general', 'General'), ('restaurant', 'Restaurant'), ('tech', 'Technology'), ('health', 'Healthcare'), ('fitness', 'Fitness'), ('creative', 'Creative'), ('business', 'Business'), ('education', 'Education'), ('ecommerce', 'E-commerce')], default='general', max_length=50)),
                ('schema', models.JSONField(default=dict, help_text='Схема props компонента')),
                ('html_template', models.TextField(help_text='HTML шаблон с переменными ${variable}')),
                ('css_template', models.TextField(help_text='CSS шаблон с переменными')),
                ('js_template', models.TextField(blank=True, help_text='JavaScript для компонента')),
                ('preview_image', models.URLField(blank=True, help_text='URL превью компонента')),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list, help_text='Теги для поиска')),
                ('usage_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_images', models.BooleanField(default=False, help_text='Нужны ли изображения')),
                ('image_slots', models.JSONField(default=list, help_text='Слоты для изображений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон компонента',
                'verbose_name_plural': 'Шаблоны компонентов',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='aigenerationrequest',
            name='cache_hit',
            field=models.BooleanField(default=False, help_text='Результат из кэша'),
        ),
        migrations.AddField(
            model_name='aigenerationrequest',
            name='cache_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aigenerationrequest',
            name='site_type',
            field=models.CharField(blank=True, choices=[('landing', 'Лендинг'), ('portfolio', 'Портфолио'), ('business', 'Корпоративный'), ('blog', 'Блог'), ('ecommerce', 'Интернет-магазин'), ('restaurant', 'Ресторан'), ('creative', 'Креативный'), ('personal', 'Персональный')], max_length=50),
        ),
        migrations.AddField(
            model_name='aigenerationstats',
            name='cache_hits',
            field=models.IntegerField(default=0, help_text='Попаданий в кэш'),
        ),
        migrations.AddField(
            model_name='aigenerationstats',
            name='popular_industries',
            field=models.JSONField(default=dict, help_text='Статистика по индустриям'),
        ),
        migrations.AddField(
            model_name='globalaistats',
            name='cost_savings',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Экономия от кэша', max_digits=12),
        ),
        migrations.AddField(
            model_name='globalaistats',
            name='popular_industries',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='globalaistats',
            name='total_cache_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aigenerationrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Обработка'), ('analyzing', 'Анализ промпта'), ('generating_structure', 'Создание структуры'), ('fetching_images', 'Поиск изображений'), ('compiling', 'Сборка кода'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('timeout', 'Таймаут'), ('ai_error', 'Ошибка AI'), ('invalid_response', 'Некорректный ответ AI')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='aigenerationrequest',
            name='style',
            field=models.CharField(choices=[('modern', 'Современный'), ('minimal', 'Минимализм'), ('creative', 'Креативный'), ('business', 'Бизнес'), ('dark', 'Темная тема'), ('colorful', 'Яркий'), ('elegant', 'Элегантный'), ('playful', 'Игривый'), ('corporate', 'Корпоративный'), ('artistic', 'Художественный')], default='modern', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='category',
            field=models.CharField(choices=[('landing', 'Лендинг'), ('portfolio', 'Портфолио'), ('blog', 'Блог'), ('ecommerce', 'Магазин'), ('corporate', 'Корпоративный'), ('creative', 'Креативный'), ('restaurant', 'Ресторан'), ('health', 'Медицина'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='style',
            field=models.CharField(choices=[('modern', 'Современный'), ('minimal', 'Минимализм'), ('creative', 'Креативный'), ('business', 'Бизнес'), ('dark', 'Темная тема'), ('colorful', 'Яркий'), ('elegant', 'Элегантный'), ('playful', 'Игривый'), ('corporate', 'Корпоративный'), ('artistic', 'Художественный')], default='modern', max_length=50),
        ),
        migrations.CreateModel(
            name='SiteStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_data', models.JSONField(default=list, help_text='Массив компонентов с данными')),
                ('global_styles', models.JSONField(default=dict, help_text='Глобальные стили (цвета, шрифты)')),
                ('seo_data', models.JSONField(default=dict, help_text='SEO мета-данные')),
                ('images_data', models.JSONField(default=dict, help_text='Данные изображений из Unsplash')),
                ('detected_industry', models.CharField(blank=True, max_length=50)),
                ('detected_site_type', models.CharField(blank=True, max_length=50)),
                ('primary_color', models.CharField(blank=True, help_text='HEX цвет', max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('compiled_html', models.TextField(blank=True)),
                ('compiled_css', models.TextField(blank=True)),
                ('compiled_js', models.TextField(blank=True)),
                ('generation_time', models.FloatField(default=0.0, help_text='Время генерации в секундах')),
                ('components_count', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_structure', to='ai_generator.aigenerationrequest')),
            ],
            options={
                'verbose_name': 'Структура сайта',
                'verbose_name_plural': 'Структуры сайтов',
            },
        ),
    ]
