# Generated by Django 5.2.3 on 2025-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0002_componenttemplate_aigenerationrequest_cache_hit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestructure',
            name='images_data',
            field=models.JSONField(default=dict, help_text='Данные изображений из Pexels'),
        ),
    ]
