# Generated by Django 5.2.3 on 2025-07-02 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0004_remove_cache_models'),
        ('portfolio', '0004_alter_portfolio_unique_together_alter_portfolio_slug'),
        ('portfolio_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTemplateAIStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата статистики', unique=True)),
                ('total_ai_requests', models.IntegerField(default=0)),
                ('total_ai_successful', models.IntegerField(default=0)),
                ('total_ai_failed', models.IntegerField(default=0)),
                ('total_regular_usage', models.IntegerField(default=0)),
                ('active_ai_users', models.IntegerField(default=0, help_text='Пользователей использовавших AI')),
                ('premium_users_count', models.IntegerField(default=0, help_text='Всего премиум пользователей')),
                ('average_ai_response_time', models.FloatField(default=0.0)),
                ('total_tokens_consumed', models.IntegerField(default=0)),
                ('popular_templates_ai', models.JSONField(default=dict, help_text='Популярные шаблоны для AI')),
                ('popular_templates_regular', models.JSONField(default=dict, help_text='Популярные шаблоны обычно')),
                ('error_distribution', models.JSONField(default=dict, help_text='Распределение ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Глобальная статистика AI шаблонов',
                'verbose_name_plural': 'Глобальная статистика AI шаблонов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Название проекта', max_length=200)),
                ('project_description', models.TextField(help_text='Описание проекта')),
                ('user_data', models.TextField(help_text='Данные пользователя для AI')),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('ai_error', 'Ошибка AI'), ('invalid_html', 'Некорректный HTML'), ('server_overload', 'Перегрузка сервера')], default='processing', max_length=30)),
                ('response_time', models.FloatField(blank=True, help_text='Время ответа AI в секундах', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Использовано токенов', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке')),
                ('ai_raw_response', models.TextField(blank=True, help_text='Сырой ответ от AI')),
                ('original_html', models.TextField(blank=True, help_text='Оригинальный HTML шаблона')),
                ('generated_html', models.TextField(blank=True, help_text='HTML после AI обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio_created', models.ForeignKey(blank=True, help_text='Созданное портфолио', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='portfolio_templates.portfoliotemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI генерация шаблона',
                'verbose_name_plural': 'AI генерации шаблонов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAIStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата статистики')),
                ('ai_requests_count', models.IntegerField(default=0, help_text='Количество AI запросов')),
                ('ai_successful_count', models.IntegerField(default=0, help_text='Успешных AI генераций')),
                ('ai_failed_count', models.IntegerField(default=0, help_text='Неудачных AI генераций')),
                ('regular_usage_count', models.IntegerField(default=0, help_text='Обычное использование шаблонов')),
                ('total_ai_response_time', models.FloatField(default=0.0, help_text='Общее время AI ответов')),
                ('total_tokens_used', models.IntegerField(default=0, help_text='Общее количество токенов')),
                ('popular_templates', models.JSONField(default=dict, help_text='Статистика по шаблонам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ai_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика AI шаблонов',
                'verbose_name_plural': 'Статистика AI шаблонов',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='aigenerationrequest',
            name='portfolio_created',
        ),
        migrations.RemoveField(
            model_name='aigenerationrequest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='aigenerationstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aigenerationstats',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aiprompttemplate',
            name='user',
        ),
        migrations.DeleteModel(
            name='GlobalAIStats',
        ),
        migrations.DeleteModel(
            name='AIGenerationRequest',
        ),
        migrations.DeleteModel(
            name='AIGenerationStats',
        ),
        migrations.DeleteModel(
            name='AIPromptTemplate',
        ),
    ]
