# Generated by Django 5.2.3 on 2025-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagepublicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapilimit',
            name='storage_limit_mb',
            field=models.IntegerField(blank=True, help_text='Лимит хранилища в MB (null = безлимитно)', null=True),
        ),
    ]
