# Generated by Django 5.2.3 on 2025-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0003_alter_sitestructure_images_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentTemplate',
        ),
        migrations.RemoveField(
            model_name='aigenerationrequest',
            name='cache_hit',
        ),
        migrations.RemoveField(
            model_name='aigenerationrequest',
            name='cache_key',
        ),
        migrations.RemoveField(
            model_name='aigenerationrequest',
            name='site_type',
        ),
        migrations.RemoveField(
            model_name='aigenerationstats',
            name='cache_hits',
        ),
        migrations.RemoveField(
            model_name='aigenerationstats',
            name='popular_industries',
        ),
        migrations.RemoveField(
            model_name='globalaistats',
            name='cost_savings',
        ),
        migrations.RemoveField(
            model_name='globalaistats',
            name='popular_industries',
        ),
        migrations.RemoveField(
            model_name='globalaistats',
            name='total_cache_hits',
        ),
        migrations.AlterField(
            model_name='aigenerationrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Обработка'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('timeout', 'Таймаут'), ('ai_error', 'Ошибка AI'), ('invalid_response', 'Некорректный ответ AI')], default='processing', max_length=30),
        ),
        migrations.DeleteModel(
            name='SiteStructure',
        ),
    ]
